### ISSUE TITLE
Sometimes Chain-Repeat Animation do not work as I expect

### ISSUE THREAD

**Issue by pangyulei** [icanzilb/EasyAnimation#2] opened 2015-06-25 14:57 UTC
```
UIView.animateAndChainWithDuration(1.0, delay: 0.0, options: nil, animations: { () -> Void in
    self.layer.borderColor = flashBorderColor.CGColor
}, completion: nil).animateWithDuration(1.0, delay: 0.0, options: UIViewAnimationOptions.Repeat, animations: { () -> Void in
    self.layer.borderColor = originBorderCGColor
}, completion: nil)
```
I expect it could flash borderColor, but not works for me.
already read the demoApp's example, can not figure out what's going wrong here, pls help :(

**Comment by icanzilb** [comment] 2015-06-25 15:05
I'll try to reproduce later today

**Comment by icanzilb** [comment] 2015-06-26 07:04
this might be a bug related to animating only layer properties in the animations block; definitely high prio on my todo list, will let you know when I upload a fix

**Comment by icanzilb** [comment] 2015-06-26 08:00
@pangyulei "but not works for me." - what exactly happens?

**Comment by pangyulei** [comment] 2015-06-26 08:46
@icanzilb I set NSTimeInterval to 1 sec, but it change borderColor immediately.

**Comment by icanzilb** [comment] 2015-06-26 08:48
okay so it just flashes very quickly between the two colors, right?

**Comment by pangyulei** [comment] 2015-06-26 08:51
@icanzilb right

**Comment by icanzilb** [comment] 2015-06-26 09:40
alright - that's a bug I'm working currently on I'll release a new pod version by end of the week to publish the fix

**Comment by icanzilb** [comment] 2015-06-29 12:50
fixed in the latest version 0.7.0 - give it a try please and let me know

**Closed by icanzilb** 2015-06-29 12:50 UTC

**Comment by pangyulei** [comment] 2015-06-29 17:30
@icanzilb works fine now! thx!
